# ===================================================================
# APPLICATION PROPERTIES
# ===================================================================
server:
  port: 0
spring:
  application:
    name: consumer-service
  cloud:
    stream:
      bindings:
        bookings:
          destination: bookings-exchange
          group: bookings-queue
  zipkin:
    base-url: ${ZIPKIN_URI:http://localhost:9411/}
eureka:
  instance:
    instance-id: ${random.value}
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}