# ===================================================================
# APPLICATION PROPERTIES
# ===================================================================
server:
  port: 0
spring:
  application:
    name: consumer-service
  cloud:
    stream:
      bindings:
        bookings:
          destination: bookings-exchange
          group: bookings-queue
eureka:
  instance:
    instance-id: ${random.value}
