version: '3'

services:
  postgres:
    container_name: Postgres
    image: "postgres:10"
    restart: always
    ports:
      - 5432:5432
  rabbitmq:
    container_name: RabbitMQ
    image: "rabbitmq:management"
    restart: always
    ports:
      - 4369:4369
      - 5671:5671
      - 5672:5672
      - 15671:15671
      - 15672:15672
  jaeger:
    container_name: Jaeger
    image: "jaegertracing/all-in-one:latest"
    restart: always
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
      - 5775:5775
      - 6831:6831
      - 6832:6832
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
