# ===================================================================
# APPLICATION PROPERTIES
# ===================================================================
server:
  port: 8080
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: import-service
          uri: lb://import-service
          predicates:
            - Path=/bookings/**
          filters:
            - RewritePath=/bookings/(?<path>.*), /$\{path}
  zipkin:
    base-url: ${ZIPKIN_URI:http://localhost:9411/}
eureka:
  instance:
    instance-id: ${random.value}
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}