# ===================================================================
# APPLICATION PROPERTIES
# ===================================================================
server:
  port: 0
spring:
  application:
    name: import-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
  flyway:
    enabled: true
    schemas: import_service
  cloud:
    stream:
      bindings:
        bookings:
          destination: bookings-exchange
  zipkin:
    base-url: ${ZIPKIN_URI:http://localhost:9411/}
eureka:
  instance:
    instance-id: ${random.value}
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}